name: Build and deploy ASP.Net Core app to Azure Web App - Onatrix
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Build with dotnet
        run: dotnet build <Onatrix>.csproj --configuration Release  # Replace with your project file
      - name: Publish with dotnet
        run: dotnet publish <Onatrix>.csproj -c Release -o ./myapp  # Replace with your project file
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp  # Pointing to the published output

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Onatrix'
          slot-name: 'Production'
          package: ./myapp  # Ensure this points to the correct output directory
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3F40D3326C134A31AA0C385470DF69D9 }}
